codecov:
  notify:
    require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project: true
    patch: true
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "header, diff"
  behavior: default
  require_changes: true